import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Footer from '@/components/Footer';
import { SearchProvider } from '@/context/search.context';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'CatWiki',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<SearchProvider>
				<body className={montserrat.className}>
					<Header />
					{children}
					<Footer />
				</body>
			</SearchProvider>
		</html>
	);
}
